### ISSUE TITLE
Refill Ammo button!

### ISSUE THREAD

**Issue by codecorsair** [CUModSquad/Camelot-Unchained#105]
For helping out with current testing, I'd like a button placed on the UI (pick a place wherever you think looks good) that will just send the /refillammo slash command to the client.  The button should live in the HUD module and make it so it can be moved around like the rest of the HUD components.

Initial button can simply have the text "Refill Ammo" on it. Art may make a picture for it, but for now the text is fine.  This is just meant to be something temporary for testing.

**Comment by Mehuge** [comment]
I am pretty sure this was completed by #106 :)
