### ISSUE TITLE
patcher: Uncaught TypeError: Cannot read property 'lastUpdated' of undefined

### ISSUE THREAD

**Issue by Mehuge** [CUModSquad/Camelot-Unchained#107]
In ``widgets\Controller\services\session\controller.ts`` ``getChannels:reducer()`` it tries to update the server list with channel status and last updated, but trips up when ``server.channelID`` is 30 because that does not exist in the ``channelDict`` map.

Found by Agoknee

**Comment by Mehuge** [comment]
Attempted the following fix:

```      const channel = channelDict[server.channelID];
      if (channel) {
        servers[key].channelStatus = channelDict[server.channelID].channelStatus;
        servers[key].lastUpdated = channelDict[server.channelID].lastUpdated;
      } else {
        servers[key].channelStatus = ChannelStatus.NotInstalled;
        servers[key].lastUpdated = 0;
      }```

However with that fix in place, after logging in, it never successfully gets the server list, instead I keep seeing 'no server selected' in console, so looks like there is more to it than just this fix, such as fixing channelDict so it knows about channel ID 30

**Comment by Mehuge** [comment]
The issue I was having with fetching server lists turned out to be the .bind() undefined function issue, ie completely separate.  So the PR submitted contains the above fix for this specific issue as the bind issue has now been fixed separately.

**Comment by codecorsair** [comment]
great!
