### ISSUE TITLE
GameDataAPI promise / error types

### ISSUE THREAD

**Issue by Mehuge** [CUModSquad/Camelot-Unchained#112]
The issue comes from `ts-lint` insisting on explicit typing, forcing use of `:any` on the value argument as in

```
webAPI.GameDataAPI.getRacesV1().then((value: any) => dispatch(something));
```
rather than just
```
webAPI.GameDataAPI.getRacesV1().then((value) => dispatch(something));
```

The promise argument type is 

```
{
  duration: number;
  problem: any;
  ok: boolean;
  status: number;
  headers: any;
  config: AxiosRequestConfig;
  data: any;
  error: Unauthorized | BadRequest | ExecutionError | NotAllowed | ServiceUnavailable
}
```

Also because error may be one of several types, I wonder if it would be better if they were all derived from a base error type

```
export interface RequestError {
  Code: number;
  Message: string;
  FieldCodes: any;
};

export interface BadRequest extends RequestError {
  Code: 500;
  Message: string;
  FieldCodes: [ FieldCodes.UnexpecifiedExceptionError ]
};
```  

And then we can use `error: RequestError` when passing `value.error` around.

OR, we could just disable `ts-lint`'s insistence of having explicitly defined types.

**Comment by Ajackster** [comment]
I don't think we should

**Comment by Ajackster** [comment]
WHOOPS sorry about that

**Comment by Mehuge** [comment]
The actual error ts-lint was throwing is:

``Unexpected parentheses around single function argument having a body with no curly braces.``
for
```.then((value) => dispatch(something))```

and doing the following works
```.then((value: any) => dispatch(something))```

seems also doing the following works

```.
then((value) => {
  dispatch(something)
})
```
As for the error argument, typescript complains that it implicitly has any type, I guess because error has more than one possible type.

``error TS7006: Parameter 'error' implicitly has an 'any' type.``

Anyway, so I can use { } in arrow functions to avoid the weird ts-lint error instead of adding :any to value argument, but for now error: any will need to stay I think.
