### ISSUE TITLE
Resolve merge conflict in .gitignore

### ISSUE THREAD

**Issue by saddieeiddas** [CUModSquad/Camelot-Unchained#146]
There is a merge conflict committed in `.gitignore` here: https://github.com/CUModSquad/Camelot-Unchained/blob/master/.gitignore#L47-L55

```
<<<<<<< HEAD
**/schema.ts
**/schema.json
**/definitions.ts
=======
game/hud/gql/
game/hud/src/gqlDocuments\.ts
game/hud/src/gqlInterfaces\.ts
>>>>>>> f8b2cd5656d7e595e3dd62dd56b6f87b81167e24
```

I am happy to create a PR for this, although I am unsure what the merge should look like.

**Comment by codecorsair** [comment]
I'll fix it up.  Thanks.
