### ISSUE TITLE
Invariant Violation: using this.refs in a library component

### ISSUE THREAD

**Issue by Mehuge** [CUModSquad/Camelot-Unchained#22]
I originally came across this issue when trying to add logic to handle the scroll position of the character selection dropdown (https://github.com/CUModSquad/cu-patcher-ui/issues/151).  It uses the QuickSelect component from camelot-unchained library, and I need to add a ref="download" to an element so I could handle it's scroll position, and I started seeing the Invariant Violation error messages.

> addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component\'s render method, or you have multiple copies of React loaded.

The error message according to the react help either means that we are trying to add a ref outside of the render method (which was not the case) or that our npm module configuration is screwed up and we are compiling in two versions of react.

Indeed, when @codecorsair had the issue in the patcher build, and I didn't, I was able to compare the compiled output from live patcher that did not work and my build which did, and the live build was an extra 20 or so KB larger.   I presume because of a second copy of react being compiled in.  JB has since fixed that issue (not sure what he did though).

Now it seems that moving chat into cu-xmpp-chat is now also experiencing the issue, and that this.refs['chatbox'] is undefined, and the Invariant Violations are being thrown, based on recent discussion in modsquad chat by @mac10688

**Comment by codecorsair** [comment]
this is no longer an issue with bundling react separately.
