### ISSUE TITLE
Issues testing library changes

### ISSUE THREAD

**Issue by Mehuge** [CUModSquad/Camelot-Unchained#27]
I ran into a couple of issues over the weekend trying to make a change and library\ and test them locally before submitting them.  

To setup for local testing I did the following (using game\hud as the example here):

    cd game\hud
    npm link ..\..\library

```npm``` is clever enough to know that ```..\..\library``` is camelot-unchained and sets up the correct links in ```AppData\Local``` and ```node_modules``` so there is no need to ```npm link``` first, then ```npm link camelot-unchained```.

**issue 1**

    cd game\hud
    npm run build:hatchery

This is failing with 

    Error: File to import not found or unreadable: cu-xmpp-chat/lib/index.scss

To work around this until there is a proper solution, @codecorsair suggested the following

    cd library
    npm i cu-xmpp-chat

**issue 2**

Compiling ```game\hud``` would not compile in the changes made to the local library.  

I eventually tracked this down to the ```"browserify":``` entry in ```package.json``` and the use of ```-u camelot-unchained```.  I had to remove that option to be able to build in my library changes for testing.  Not sure what that option is doing or if we need it or why it wouldn't pull in the local copy of the library.

**Comment by codecorsair** [comment]
from now on use the node-sass-importer script rather than using the sass-npm-impoter.js file from the camelot-unchained lib. 

this change requires the package be installed and then change the build:sass script to `"build:sass": "node-sass src/index.scss -o build/css --importer node_modules/node-sass-impoter/node-sass-impoter.js",`
