### ISSUE TITLE
Show offline servers

### ISSUE THREAD

**Issue by codecorsair** [CUModSquad/Camelot-Unchained#70]
Currently we can only see online servers, or servers that are specific to a channel on the patcher.  The patcher should be aware of expected server and display them as offline if they are not available.

**Comment by sysrage** [comment]
Conversation from Trello:

@sysrage - Current patcher does seem to show offline servers now but it needs improvement. We need something in the API to show whether a server is online or offline so various UI elements can act appropriately (don't let user 'play now' on an offline server, don't poll for player count on offline server, etc.).

@saddieeiddas  - i have looked into this and would agree that the current offline servers are being shown. I am not sure how to make this better without the API to provide the online/offline state as @sysrage says.

**Comment by codecorsair** [comment]
Done.
