### ISSUE TITLE
Widget visibility should be handled by the HUD

### ISSUE THREAD

**Issue by sysrage** [CUModSquad/Camelot-Unchained#74]
Currently, the visibility of HUD widgets are handled by each individual widget. @codecorsair has requested that the HUD take control of overall widget visibility. This will prevent unnecessary rendering of completely hidden widgets.

**Comment by sysrage** [comment]
This feature is blocking acceptance of PR #59.

**Comment by codecorsair** [comment]
completed by https://github.com/CUModSquad/Camelot-Unchained/commit/48269b799b781f5a007ddaf11cdded1f3c6ef335
