### ISSUE TITLE
Character/Server Lists not auto-refreshing after closing client

### ISSUE THREAD

**Issue by sysrage** [CUModSquad/Camelot-Unchained#75]
The character lists, server lists, and likely other items are no longer auto-refreshing after closing the game client. Items like the 'last login' value are constantly updated before launching the game. They only stop updating when the game is launched and don't resume when the game is closed. This applies to server states and other values, as well.

**Comment by sysrage** [comment]
I looked at this awhile back, but couldn't figure out why things stopped getting updated.

**Comment by codecorsair** [comment]
This issue will be going away with the next iteration of the patcher I have planned after my current or next tasks.

**Comment by codecorsair** [comment]
Done.
