### ISSUE TITLE
First time patcher startup not auto-selecting character

### ISSUE THREAD

**Issue by sysrage** [CUModSquad/Camelot-Unchained#76]
The first time you launch the patcher, it's missing several sidebar components. You have to reselect Hatchery (or any server) before it starts showing the rest of the sidebar.

https://i.imgur.com/GXbNhuE.jpg

I assume this has something to do with the auto-select stuff failing when there are no values saved in localStorage.

**Comment by codecorsair** [comment]
Is this still an issue?  I haven't seen it since my latest change to the sidebar.

**Comment by sysrage** [comment]
I just re-tested this and the behavior has changed. The sidebar components all show correctly now, but if you select a server that already has characters, the 'first' character won't actually be selected. If you try to select the same character, nothing happens.

So, I think a 'select' needs to be auto-performed on the character with index of 0.

**Comment by codecorsair** [comment]
Fixed.
