### ISSUE TITLE
Launcher UX design improvements

### ISSUE THREAD

**Issue by codecorsair** [CUModSquad/Camelot-Unchained#78]
Our patcher leaves a bit to be desired as far as usability goes.  so @Heartfyre is working on some UX design improvements.

**Comment by codecorsair** [comment]
![launcher_ver1_main](https://cloud.githubusercontent.com/assets/9878445/18714340/723641a2-7fe3-11e6-9cbc-2c034b4df6ab.png)

**Comment by codecorsair** [comment]
![launcher_ver1](https://cloud.githubusercontent.com/assets/9878445/18714352/794c61a6-7fe3-11e6-88c2-c685c114b203.png)

**Comment by jamkoo** [comment]
I like idea of moving the server selection to the bottom!  Giving the main content more space is always awesome. 

I'm not a fan of the border art style, but I do like elements bleeding out of the window. Not sure if we have that capability yet. @codecorsair do we? 

Is there a location for showing how many people are in the server per realm? 

I know some mad comments of the notification feeling a little heavy on the content side. But i would like to try it out and see how the community responds to it. I think it could work, and if it does it's nice to have it all in one place.

**Comment by codecorsair** [comment]
@jamkoo we will have the capability to do borderless with bleeding art stuff soon, so that will be possible.

**Comment by codecorsair** [comment]
@Heartfyre where / how do we access patcher settings and what would that look like?  How do we control music quickly / sound effects?

**Comment by Heartfyre** [comment]
Just so you know, the border is completely optional. The launcher design will work as well without it. Also it will be possible to add another design if wanted. I designed everything the way, so that the border style might be removed. 

My biggest concern problem with it is, that it will be a problem with resizing. It might look strange, depending on how it'll be done. 

Regarding the server population and other infos - Those elements, like the dropdown list for servers, are modular and the displayed infos can be altered and changed any time, depending on what infos are needed and wanted.

This is more baout the design and the UX. The content can be changed any time, as it is dynamic enough.

**Comment by JoelTerMeer** [comment]
Saw the optional skins for realm-pride - but didn't see a settings tab or button to pop up patcher settings and change skins. Am I blind or is it omitted?

**Comment by codecorsair** [comment]
What would the "favorites" heart selection on a game, server, or character do?

**Comment by Heartfyre** [comment]
Those will always be pre selected, if some logs in, no matter what had selected when he logged off. It's like a favorite selection to qucik start. It's just an idea, maybe not the most important thing to have.

**Comment by codecorsair** [comment]
So you would then only allow a single thing to be "hearted" at a time in each grouping?

**Comment by Heartfyre** [comment]
Right. You could also just "heart" the game and the server, but leave the character selection open. The main goal is, that the user does not have to select everything with every start again and again. Most people will stick to one server and I guess to one character, maybe two.

**Comment by jamkoo** [comment]
@Heartfyre could it be better if we just leave the last selected char/server?

**Comment by codecorsair** [comment]
The more I think about it the more I think we need to have the patcher have a normal uniform straight border.  I really love the non-uniform edges, and they look great when you have a more typical game patcher that is in the center of your screen and there until you launch the game and non-resizeable.  Our patcher will persist as you play the game, be used more as a desktop application so the standard window shape would be needed to allow users to maximize properly, dock the app, organize the app in the corner of their screen and whatnot.

**Comment by tryadelion** [comment]
i'd also leave the last selected rather than hearts, and i have conflicting feels on the borders. they look amazing, but JB has a point , the launcher is meant to be some kind of overwolf/discord client too, so you  might wanna have it minimized, docked, full screen on another window....  i'd also make the dropdown arrows and the smalltext more visible, i can barely see it on my laptop. overall awesome design, loving it.

**Comment by Heartfyre** [comment]
@jamkoo - That could be another way, but the last used character/server might not always be the favorite selection. To be honest, we a re talking about comfort options here. Nothing which is important, to have the launcher or the game working. It's just something I was thinking about, and we can always discuss the best approach, also regarding time and usefulness/profit.

@codecorsair - As I said, it won't be a problem to remove that border. I'll create another version until friday. Just to be able to compare it. The question is - Do you want it to be uniform and without a border, but frameless, like without a Windows frame. Or do you want it the way it is on the actual launcher, where you have the Windows frame around it?

**Comment by sysrage** [comment]
First off, this looks beautiful. Great job. Some feedback:

- I agree with @jamkoo. I think, instead of hearts and/or manually selecting favorites, it should just auto-select the last-selected server and character. This *was* working on the current patcher and made logging in work quite well.

- I think we'll need a way to show both 'server population' as well as the number of characters that user has on each server. As you said, this can be fit in somewhere in your current design. We just need to find a good place for all the info.

- Similar to above, the required access level should be shown somewhere. This can be where the 'type' (pvp, pve, etc.) is in your mockup, since I don't think there will be more than one server type to begin with. Ultimately, this can be removed, once the login API tells the user what access level their account is. We can then only show servers the user has access to.

- Instead of having 'chat' listed in the top menu, I recommend having it be a separate widget. By default (user-definable), it should be a small icon hanging off the right edge of the patcher. If you click it, it can expand to multiple levels. One level showing only the 'rooms' the user is in and any new message counts from those rooms. This 'smaller' level could also show a friends list, allowing easy instant messaging to friends. A second bigger level would then show the full chat rooms.

- As @codecorsair said, we need the quick toggles for sound/music.

**Comment by jamkoo** [comment]
@Heartfyre i was thinking removing the heart would allow space to somehow put in the population per realm.

**Comment by codecorsair** [comment]
@Heartfyre frameless.

**Comment by Heartfyre** [comment]
Okay. I read all you comments until this point. I will make those changes and try out a few things. I won't change the big image posted above, as it was a lot of work. Maybe later, when we decided on everything, but in the end, as long as only the frame and some infos change, I don't think I need to add a new overview. :)

**Comment by Heartfyre** [comment]
Hey guys,

I did a few changes to the launcher layout, which I will describe further down below.
![woborder](https://cloud.githubusercontent.com/assets/20871500/18746795/d4a2e69c-80c9-11e6-9c7f-6147d81c19b0.png)

First and most important – I did remove the border from the launcher. Therefor I moved the window options (minimize, etc) to a position above the menu. I also added toggle icons for sound and fx. Those icons are just temporary and need to be replaced later, as I didn’t have better ones.

**Comment by Heartfyre** [comment]
Below you can find an example of another feature – Messages. I didn’t have the time to add them yesterday, but wanted to do so today. Those „messages“ can be used to give quick infos or warnings to the users, which they will see directly when they open up the launcher. This is just an example. There might be different colour variations for different purposes, like green, blue or whatever.

![warning](https://cloud.githubusercontent.com/assets/20871500/18746820/ef9701ae-80c9-11e6-954c-f11dc85d728d.png)

**Comment by Heartfyre** [comment]
Another thing I wanted to add were info boxes, which can be used on the front of the launcher (within the slider). As there is more space available with the new design, CSE would be able to add whatever content (html, etc) to the launcher, to present infos, products, and so on. If needed they can add info texts or videos, or… Those are just examples!

![infobox1](https://cloud.githubusercontent.com/assets/20871500/18746832/fd182038-80c9-11e6-977b-759913aaf685.png)
![infobox2](https://cloud.githubusercontent.com/assets/20871500/18746833/fd1a0c04-80c9-11e6-9d78-ffb897f3fd75.png)

**Comment by Heartfyre** [comment]
I did change a few things on the dropdown buttons, mainly on the server selection. I added an online counter and changed the icons for the server status. I also removed the „heart“ from the dropdowns and added a new icon to the server selection. This is just another idea! It (the icon) can still be removed completely. Please see the next post for more infos!

![dropdowns](https://cloud.githubusercontent.com/assets/20871500/18746844/0a72a74e-80ca-11e6-846f-bf4e9e3bc5a3.png)

**Comment by Heartfyre** [comment]
I was thinking about a link to another launcher „site“, form the server selection, which will give the user more insight about the server itself, like graphs, stats, charts and so on.

An idea is, that the user would be able to open the server stat window and monitor it while playing. So the data presented would be live data, which would be updated every few seconds. 

Again, this is just an idea! Also the design is just for demonstration purposes, nothing final or finished. I am not happy with it, but again, it’s just for presentations.

![serverstats](https://cloud.githubusercontent.com/assets/20871500/18746857/17ff568c-80ca-11e6-9811-d0d61b711bf5.png)

**Comment by Heartfyre** [comment]
Last but not least – sysrage asked to remove the chat menu item. I feel that this is something we need to discuss, before I come up with a solution. I personally don’t like the idea of hiding things behind an icon. 

The whole idea of the redesign for the launcher was, at least a part of it, to have things visible, without the user needs to search for them.

But that’s just my opinion. I think there’re different ways. Also nothing iss et in stones and especially the menu can be altered everytime.

**Comment by tryadelion** [comment]
I like the new charts , http://www.chartjs.org/ is an amazing library for doing this kind of reactive features and things.  i still have trouble in both of my screens with the "select a character?" , remove character icon, etc dark black. everybody else see them right?

**Comment by Heartfyre** [comment]
Hey @tryadelion,

it's possible, that some parts might look a bit dark on certain settings. My main screen might be a bit too bright, so that it might be darker on other screens. In the end the best way to test things like colour is, when the coding starts, while it's also much easier to play with different colour variations, lighter or darker.

I might check it again, if I rework those parts, if there's need for more changes.

**Comment by Mehuge** [comment]
"Wrong Password"

Is this information leakage?  

That is, does it allow an attacker to discover valid user names where there isn't any other way to do that.  Ofc if the registration process for the game allows an attacker to discover valid emails, then the point is moot, but if the registration process doesn't leak that information, then saying 'wrong password' does and probably should be changed to be less specific to avoid leaking that information.

**Comment by codecorsair** [comment]
@Mehuge "Wrong password" or w/e error information is shown is irrelevant to the design.  It's just there to show that there will be some kind of error information.

**Comment by Mehuge** [comment]
@Heartfyre could chat be displayed in a similar way to the info panels you talked about rather than cover the entire patches as it does now?

https://github.com/CUModSquad/Camelot-Unchained/issues/78#issuecomment-248879528

**Comment by codecorsair** [comment]
If chat fills up just the middle region I think this would work just fine.  Leaves the patch functionality on the bottom functional, the top bar functional, just replaces the middle content.

**Comment by Heartfyre** [comment]
All content is supposed to fill the middle part. I guess what Mehuge is refering to is, to have boxes, that leave space in the content part, so that you'll see the/ a background. 

It can be done without any problem, as it's just html and css. The question is, if we or CSE want to. The thing is - In my opinion we should use all the available space, as it is not much and it's much less, if the user resizes the launcher to a minimum. 

But sure - It can be done. The content part is just a container, where everything is possible, like with a normal website for example. We have all the possibilities. :)

**Comment by sysrage** [comment]
The reason I thought chat should be an isolated widget on the patcher is so it can be used, no matter what else you're doing with the patcher. That way you could be connected to chat and have active conversations while you're looking at the news section or something else. if there's always a chat icon and then it starts sliding out in different increments, it'll be obvious when there's a new message for you. You can then also have chat partially showing while still reading something else like news.

If nothing else, we should at least have badges up on the Chat menu item showing unread count.

**Comment by Heartfyre** [comment]
Okay, I get what you mean. I think in the end it's more of a technical, than a design issue. Not sure what the launcher is capable of and what can be done, like with running widgets (chat) outside the main window, but still as part of it. Form a design point of view I can design anything if wanted, but I can't say if it's possible.

**Comment by Heartfyre** [comment]
Hello gentleman,

as asked by MR. JB himself, I created a settings panel for the launcher. 

I tryed something different, which has been requested before, if I recall correctly. I didn't use all of the space, but created gaps between certain elements, which as well exposes the background. It's a test and we can decide if we like it or not. If so, we should stick to the one or the other solution, to have a consistent solution.

Sorry, if the design again is a bit too dark. I'll work on it next week and create a colour palette for JB, which he can use to evolve from there. 

Without further ado:

![settings](https://cloud.githubusercontent.com/assets/20871500/18952890/190ae320-864c-11e6-82d9-83638694a728.png)

**Comment by codecorsair** [comment]
@Heartfyre looks great.  Not sure whether I would prefer the space between sections or a solid background like the rest of the patcher... but that's an easy thing to build both ways and see how it looks.  

On the right description pane, what is shown if you are not currently hovering over an option?

**Comment by Heartfyre** [comment]
> On the right description pane, what is shown if you are not currently hovering over an option?

Wasted space... Therefor I was thinking, if a tooltip or something would be better. But then again, you don't have much space in a tooltip. Another way would be to put the desicrption beneath the single options, which would/ might cause a lot of clutter.

**Comment by codecorsair** [comment]
How about adding a ? icon thing next to each option which when clicked slides out that description panel from the right side?

**Comment by jamkoo** [comment]
awesome work Heartfyre!
Just wanted to suggest something for the server select dropdown. short hand the region (ENG, GER) and replace the total online players with showing XXXX(red) XXXX(blue) XXXX(green) or some other way to show each realm and how many people are in that realm. I think it's more important to show the amount on each realm than it is to show the total amount of people online.

**Comment by Heartfyre** [comment]
Might be an option, yes. So we can combine the best of both worlds. ;) Do you need a redesign for it, or will you do it based on the version above?

@jamkoo - That would be an easy thing to do I guess. As I said before, in the end it all depends on what data is accessable on the launcher and the rest of it is just positioning and placement. ;) If needed, I can do a design of it, but I think it shouldn't be a problem to replace/ change the used infos on the design. I just wasn't sure what exactly you guys wanted to show to the user. :)

**Comment by codecorsair** [comment]
No, I don't need a redesign on either.

**Comment by codecorsair** [comment]
Looking awesome... a few more things I'd like to see.

- Offline mode on the patcher, what does the patcher do to tell the user it can't connect to the internet.

- What does the patcher show when it can not connect to our Patch Server but it has internet access, basically means our patch server is offline or they are blocking the ports we use.

- How does the patcher notify you that it needs to update itself, I would like some kind of notification with a button at least to click and say update now sort of thing.  Or does it just close and update itself without warning... probably a bad user experience in this case.

**Comment by Heartfyre** [comment]
I can do it based on the messages, shown here: [Messages UI](https://github.com/CUModSquad/Camelot-Unchained/issues/78#issuecomment-248879445)

I think it's clearly visible and can changed in size and colour and shouldn't be a problem to add a button to it as well.

Would that suit your needs? I can create a concept for it if you'd like. Wouldn't take too much time and you would see, what it looks like.

Or did you had something different in mind?

**Comment by codecorsair** [comment]
Simple enough and should work I think

**Comment by Heartfyre** [comment]
Okay. I'll create a concept for you. Guess I'll have it for you by tommorow. :)

**Comment by codecorsair** [comment]
if it's just text or adding a button in that alert message area... I don't need to see a concept of it.

**Comment by Heartfyre** [comment]
Okay, that's fine with me. Less work for me. ;) - Let me know, if you need anything else. Now or later. :)

**Comment by Heartfyre** [comment]
After talking to JB and the other folks at CSE, we decided to rework a few colours, to have a bit of more contast. Below you can find a first version, where I tryed a few colour setups. Non of them are final or at least they don't need to. They're just ideas and a starting point, from which we can advance, if necessary.

I, if wanted, can create more versions, of different elements, if we decided, which colour we want to aim for. For the moment the shown preview is just what it is - A preview.

![overview](https://cloud.githubusercontent.com/assets/20871500/19851451/3c890540-9f5e-11e6-89e8-030dd759bece.png)

**Comment by Heartfyre** [comment]
Here's another version of the golden one, with a "launch button", which stands out more from the others.

Launch button is having #a68d72 as bg colour and #796753 as 1px border. I also changed the font weight to semi bold. Another or additional option might be, to make the text all caps.

![golden2](https://cloud.githubusercontent.com/assets/20871500/19858013/2a9b33f4-9f80-11e6-97c2-14459d693ef7.png)

**Comment by Heartfyre** [comment]
Hey, it's me again! Here's the login, with the new colour profile added to it. 

I did change the colour of the links and infos below the input boxes as well. It's just another variant. You might want to stick with the grey, like it is now. Just wanted to add another variant to it.

Colour: Input border and font (non hover state) = #54483a - Links (like forgotten pw) = #483e32 - Buttom colours = see post above

![login](https://cloud.githubusercontent.com/assets/20871500/19859075/4cb97f5a-9f84-11e6-93f0-d5798c4d0739.png)

**Comment by codecorsair** [comment]
Closed for now.
