### ISSUE TITLE
100s of pending API requests

### ISSUE THREAD

**Issue by Mehuge** [CUModSquad/Camelot-Unchained#80]
If the API polling for servers or characters is slow, the patcher ends up queueing 100s of overlapping, pending, requests.  Either the previous request should be aborted, or probably kinder to the server would be to wait for a timeout before queueing the next request.

Using a setTimeout rather than a setInterval might be a better way to do the polling.  I don't think the interval between polls is critical, so we don't need to do anything fancy.  Just setTimeout(query, 1000) after dealing with the previous request.

![image](https://cloud.githubusercontent.com/assets/99895/18800637/f890c116-81d5-11e6-8414-0399f7ba1386.png)

**Comment by codecorsair** [comment]
resolved with https://github.com/CUModSquad/Camelot-Unchained/commit/133206b492380ecf2e1faae671624485a17523fe
